on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: grantmcconnaughey/lintly-flake8-github-action
